### ISSUE TITLE
Title bar shows wrong icon under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.qbittorrent.qBittorrent#1]
![qbittorrent](https://user-images.githubusercontent.com/15967631/37556760-2aabd1c0-29d9-11e8-83e2-407dedc58e20.png)

**Comment by TingPing** [comment]
Try again once this build is done and you get the update: https://flathub.org/builds/#/builders/2/builds/185

**Comment by glaubersm** [comment]
Solved! Thank you TingPing.
