### ISSUE TITLE
Change "--filesystem=host" to "--filesystem=xdg-download"

### ISSUE THREAD

**Issue by magical-heyrovsky** [flathub/org.qbittorrent.qBittorrent#104]
There is no reason why qBittorrent should have access to the entire host.  I changed it to `xdg-download` on my computer and it works without any problems. Only give the permissions really needed, `--filesystem=host` is not one of them.

**Comment by Chocobo1** [comment]
>There is no reason why qBittorrent should have access to the entire host. 

Some users have their own dedicated/complex directory structure which may not be rooted in `xdg-download`. For example an usb disk or a network drive.

**Comment by Chocobo1** [comment]
>There is no reason why qBittorrent should have access to the entire host.

Actually it is not unrestricted as one would thought, see: https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

>Maybe there really is a way to use more restrictive paths than host without sacrificing program usability. 

Since `host` is already restrictive enough, I doubt there is room to improve it. Closing issue.

**Comment by therealmate** [comment]
> > There is no reason why qBittorrent should have access to the entire host.
> 
> Some users have their own dedicated/complex directory structure which may not be rooted in `xdg-download`. For example an usb disk or a network drive.
> 
> Maybe there really is a way to use more restrictive paths than `host` without sacrificing program usability.

qbt has support for portals, which solves this issue

**Comment by Erick555** [comment]
If you remove host permission then app will lost access to user files after update until they re-add them. It's quite disruptive change.

**Comment by Chocobo1** [comment]
>Also the ideal manner of sandboxing is to only give the app what it needs, so it is better if the rules are tightened if no functionality is lost.

Basically I agree but what about other paths I mentioned: `For example an usb disk or a network drive`?
Will `xdg-download` (or any other setting) allows it?

**Comment by Erick555** [comment]
Qt itself is aware of portals. Accessing usb disk or network drive is no different than any other directory. You can remove host permission and access any path chosen from file dialog right now. Only the pre-existing torrents outside xdg-download won't be available  - they would need to be re-added.

**Comment by Chocobo1** [comment]
>Qt itself is aware of portals. Accessing usb disk or network drive is no different than any other directory. You can remove host permission and access any path chosen from file dialog right now. 

Thanks for explaining!
Another thing worth mention is, libtorrent only use OS API for accessing files so it won't know about portals and not every operation will re-ask user for permission.

>Only the pre-existing torrents outside xdg-download won't be available - they would need to be re-added.
>
>If you remove host permission then app will lost access to user files after update until they re-add them. It's quite disruptive change.

This is especially disruptive if one has many torrents store in the affected folder/path which means qbt became unwieldy for those big seeders and this would drive them away.
IMO users that wishes to tighten their security should override this setting themselves instead of enforcing it on everyone as it clearly affect normal program usage in some conditions.
