### ISSUE TITLE
qBittorrent has two entries in Discover app store

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.qbittorrent.qBittorrent#13]
Hi
I use Discover app store on my system to install apps from flathub, I noticed two entries for qBittorrent.
I use Arch Linux, KDE Plasma 5.13.4 desktop environment, flatpak 1.0.1.

![discover](https://user-images.githubusercontent.com/15967631/44818369-391b6500-abbf-11e8-80ab-04fba5d40caa.png)

**Comment by TingPing** [comment]
The correct solution to this is convincing upstream to name their app-id the same as this.

**Comment by eszlari** [comment]
With 4.1.6 this fixed now, distros just have to update their version.
