### ISSUE TITLE
Taskbar icon missing after upgrading to 4.6.0

### ISSUE THREAD

**Issue by r2rX** [flathub/org.qbittorrent.qBittorrent#139]
Hello there,

Just wanted to report that, after upgrading to 4.6.0, the taskbar entry is present but the icon itself is missing/blank.

![icon](https://github.com/flathub/org.qbittorrent.qBittorrent/assets/18622885/ac0fde5f-a9f9-4854-825e-7126d645ebc3)

Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.10
Kernel Version: 6.5.8-200.fc38.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 9 5900HX with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6800M
Mesa Drivers: mesa-git 24.0.0

**Comment by 0-ks** [comment]
I have the same problem described by r2rX, on Arch Linux, and KDE Plasma 5.27.9:

![ksnip_20231111-155120](https://github.com/flathub/org.qbittorrent.qBittorrent/assets/70665895/a4d174e4-824c-4c15-9c2e-0331f2739ec2)

Although I just installed the Flatpak version and I don't know if It was working before 4.6.0 update or not.

**Comment by Erick555** [comment]
Do you mean the tray icon? It works for me on recent Arch Linux & KDE Plasma.

**Comment by 0-ks** [comment]
Yes, the tray icon, I tried installing the **Flatpak** qBittorrent from **Flathub** in a VirtualMachine running a fresh install of Fedora Kinoite and ArchLinux, in both Wayland and X11 tray icon is missing and It doesn't give me any errors in the terminal.

But on the same Fedora Kinoite setup, when I install the qBirrorrent **Flatpak** from **Fedora**'s remote, tray icon shows up!

**Comment by Erick555** [comment]
According to this [comment](https://old.reddit.com/r/kde/comments/17ubkuk/qbittorrent_invisible_tray_icon_how_to_fix_it/k94yigm/) setting "Use Icons from system theme" fixes this (not flatpak related).

**Comment by r2rX** [comment]
> According to this [comment](https://old.reddit.com/r/kde/comments/17ubkuk/qbittorrent_invisible_tray_icon_how_to_fix_it/k94yigm/) setting "Use Icons from system theme" fixes this (not flatpak related).

Interesting. I can confirm that this settings does indeed display the icon properly. Nice fine, @Erick555.

**Comment by 0-ks** [comment]
> According to this [comment](https://old.reddit.com/r/kde/comments/17ubkuk/qbittorrent_invisible_tray_icon_how_to_fix_it/k94yigm/) setting "Use Icons from system theme" fixes this (not flatpak related).

Indeed it does fix the problem! Thank you.

But I still don't understand why the local package from Arch extra repo and the Flatpak from Fedora remote don't have this problem?

While not a problem for me, if someone wants to use the default icons, they have to live with the invisible tray icon.

**Comment by 0-ks** [comment]
> > But I still don't understand why the local package from Arch extra repo and the Flatpak from Fedora remote don't have this problem?
> 
> AFAIK Arch and Fedora use qt6 while flathub uses qt5 - this may make difference. qt6 has different issues with theming so perhaps it would stay like this for a while.

That makes sense! Fedora uses Qt6.5.2 and Arch Qt6.6.0.

**Comment by r2rX** [comment]
Just wanted to let everyone know that with the update to 4.6.1, the taskbar icon is showing properly again (without needing to toggle the 'Use Icons from system theme' option as a workaround).
