### ISSUE TITLE
QBittorrent tray icon is not visible.

### ISSUE THREAD

**Issue by Shished** [flathub/org.qbittorrent.qBittorrent#14]
OS: openSUSE Tumbleweed
DE: Gnome-Shell 3.28 + TopIcons Plus extension
Flatpak 1.0.0

When qBittorrent is launched, its tray icon is not visible, its just an empty space.
Here is a terminal output:
```
flatpak run org.qbittorrent.qBittorrent 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
QSystemTrayIcon::setVisible: No Icon set
```

**Comment by veridiam** [comment]
@Shished once this is merged you should install [KStatusNotifierItem support](https://extensions.gnome.org/extension/615/appindicator-support/)

if you want the changes now you can override with `flatpak --system override org.qbittorrent.qBittorrent --own-name=org.kde.StatusNotifierItem-2-2`

**Comment by Shished** [comment]
I installed the extension and did this command but tray icon still didn't appeared.
Terminal shows this

> failed to register service "org.kde.StatusNotifierItem-2-2"

**Comment by Eonfge** [comment]
Issue is still open and the bug is still there
```
eonfge@eonfge-at-Ubuntu:~$ flatpak run org.qbittorrent.qBittorrent 
Gtk-Message: 18:27:34.426: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:27:34.427: Failed to load module "canberra-gtk-module"
failed to register service "org.kde.StatusNotifierItem-2-2"
```
