### ISSUE TITLE
Free space not showing on status bar webui

### ISSUE THREAD

**Issue by alexnt85** [flathub/org.qbittorrent.qBittorrent#144]
I moved from native installation to flatpak. I noticed that there is no information for disk free space availability and  says "free space: unknown" on webui.

**Comment by Erick555** [comment]
It correctly shows available free space on adding torrent dialog though. Maybe webui uses different technique which is blocked by sandbox.

**Comment by alexnt85** [comment]
> It correctly shows available free space on adding torrent dialog though. Maybe webui uses different technique which is blocked by sandbox.

I checked and doesn't show correct free space on dialog either, it showed some MBs instead of GBs. The save path is on an external hdd. Maybe this is the reason. I need webui because qbt is on another machine and I need free space information when accessing from webui. I returned to old 4.5.2 native version, sadly.

**Comment by Erick555** [comment]
Yes it could be related to external drive. You may try running with `--device=all` permission:

`flatpak run --device=all org.qbittorrent.qBittorrent`

**Comment by alexnt85** [comment]
> --device=all

Not ideal for me, too permissive. I will stay on native at the moment and wait for an update to the latest. I just wanted to try latest version because of an issue on the older 4.5.2. Thnx!

**Comment by Erick555** [comment]
The app has `--filesystem=host` permissions already and you can't get any worse than that.
