### ISSUE TITLE
qbittorrent does not allow it to be modified/configured

### ISSUE THREAD

**Issue by flokosx** [flathub/org.qbittorrent.qBittorrent#156]
When I try to change some configuration, it simply doesn't happen: when starting the program, the settings return to their initial state (default) as if I had just installed it, even that warning message regarding shared files appears.

I'm using the flatpak version on a newly installed Kubuntu 24.04

Any tips on how to make it work correctly?

**Comment by flokosx** [comment]
Thanks to colleagues on other forums, I managed to solve my problem. I don't understand much about the technicalities of the thing but it's working as expected now.

in short, for a beginner like me, I installed:
sudo apt install apparmor-utils

them:
sudo aa-disable /usr/bin/bwrap

**Comment by Erick555** [comment]
yes, there was recent regressions regarding apparmor & flatpak in ubuntu: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811
