### ISSUE TITLE
Update org.freedesktop.Platform.

### ISSUE THREAD

**Issue by ndiruhniu** [flathub/org.qbittorrent.qBittorrent#168]
qBittorrent is still using org.freedesktop.Platform branch 23.08. Could you update it to 24.08?

**Comment by Erick555** [comment]
it's using kde [platform](https://github.com/flathub/org.qbittorrent.qBittorrent/blob/master/org.qbittorrent.qBittorrent.yaml#L2). It could update to recently released [6.8](https://discuss.kde.org/t/flatpak-org-kde-sdk-6-8-runtime-is-now-available/24717)

**Comment by Chocobo1** [comment]
>It could update to recently released [6.8](https://discuss.kde.org/t/flatpak-org-kde-sdk-6-8-runtime-is-now-available/24717)

No problem using newer versions but it should only be done with a major qbt release.

**Comment by ndiruhniu** [comment]
> it's using kde [platform](https://github.com/flathub/org.qbittorrent.qBittorrent/blob/master/org.qbittorrent.qBittorrent.yaml#L2). It could update to recently released [6.8](https://discuss.kde.org/t/flatpak-org-kde-sdk-6-8-runtime-is-now-available/24717)

But when I try to remove org.freedesktop.Platform branch 23.08, I get this message:
Info: applications using the extension org.freedesktop.Platform.GL.default branch 23.08:
   org.qbittorrent.qBittorrent

**Comment by Erick555** [comment]
you can remove `org.freedesktop.Platform//23.08` but not `org.freedesktop.Platform.GL.default//23.08`
