### ISSUE TITLE
Title bar shows incorrect icon under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.qbittorrent.qBittorrent#18]
qbittorrent 4.1.3
distribution: KDE neon Developer Edition
KDE Plasma: 5.14.80
Qt: 5.11.1
KDE Frameworks: 5.51.0
flatpak 1.0.1-0ubuntu0.1

![qbittorrent](https://user-images.githubusercontent.com/15967631/46910388-5ad76e00-cf19-11e8-9c82-7267edc5e04e.png)

**Comment by glaubersm** [comment]
The icon is still incorrect in qBittorrent 4.1.5.

**Comment by eszlari** [comment]
fixed in: https://github.com/flathub/org.qbittorrent.qBittorrent/commit/cd63b3ba761562ce82a1ac82ebaa7fec31fb0e8a
