### ISSUE TITLE
Why can't I see the software version in Gnome Softwares/Ubuntu Softwares?

### ISSUE THREAD

**Issue by laichiaheng** [flathub/org.qbittorrent.qBittorrent#20]

**Comment by TingPing** [comment]
Because upstream doesn't put `releases` in their appdata file: https://github.com/qbittorrent/qBittorrent/blob/master/dist/unix/qbittorrent.appdata.xml

You can request them to do so.

**Comment by eszlari** [comment]
https://github.com/qbittorrent/qBittorrent/commit/b917f4ed01836a4517f74af889a23df8df3e5f2a
