### ISSUE TITLE
Problems with the tray icon. Gnome.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.qbittorrent.qBittorrent#22]
In Ubuntu 18.04, Gnome Shell with the extension "Topicon plus" the icon disappears when the screen goes down. (also happens to telegram)

With the native extension of Ubuntu "Ubuntu appindicators" the icon is never seen.

P.S. The icon is disproportionate and does not allow monochrome.

**Comment by eszlari** [comment]
Is this flatpak specfic? Does it work in the distro version?

**Comment by alexb3d** [comment]
I have no idea, I haven't used it for a long time.
