### ISSUE TITLE
Gnome theme icon not used

### ISSUE THREAD

**Issue by namannehra** [flathub/org.qbittorrent.qBittorrent#23]
qBittorrent from Flathub is not using the Gnome theme icon. qBittorrent from distribution's repo uses correct icon.

Flathub
![Screenshot from 2019-03-19 01-05-08](https://user-images.githubusercontent.com/8452248/54558196-1ded3700-49e3-11e9-8496-6f9e120b3321.png)

Distribution's repo
![Screenshot from 2019-03-19 01-05-13](https://user-images.githubusercontent.com/8452248/54558218-2e9dad00-49e3-11e9-9bc1-1e4423a1805e.png)

Icon theme: Flat-Remix
Distribution: Fedora 29

**Comment by TingPing** [comment]
The icon theme needs to provide icons with the name `org.qbittorrent.qBittorrent` (probably with a symlink to the old name).
