### ISSUE TITLE
Torrent files downloaded by Firefox doesn't start with Qbittorrent

### ISSUE THREAD

**Issue by Robiocop** [flathub/org.qbittorrent.qBittorrent#26]
Hi
My config : qBittorrent 4.1.5 and KDE Neon 5.15
Linux : 18.04 / Libtorrent 1.1.12.0 / Qt 5.12.0

When I downloaded torrent files with firefox, they doesn't start automatically with Qbittorrent. I need to double click on it.
I've tryied to modified the applications settings in the browser. No effect.
Note : this problem appear since I've installed Qbittorrent by the flatpak.

Until now, the file was add to Qbittorrent after the brower downloaded the torrent file.

Thanks for your help.

**Comment by eszlari** [comment]
Both, file associations and magnet links, work here (Kubuntu 20.04, Plasma 5.18.4, Firefox 75). Must be a misconfiguration on your side.

**Comment by Robiocop** [comment]
Thanks. Now it's fixed with the different updates since this issue.
