### ISSUE TITLE
latest update crashes when adding a torrent

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.qbittorrent.qBittorrent#32]
Latest update to the qbittorrent flatpak (4.2.0) crashes when adding a torrent. I think I found an issue about it on the qBittorrent issue tracker but I'm not 100% certain it's the same issue.
https://github.com/qbittorrent/qBittorrent/issues/11511

For now I downgraded to flatpak.

**Comment by Erick555** [comment]
Works for me. maybe you could try with fresh profile by renaming `~/.var/app/org.qbittorrent.qBittorrent` to `/.var/app/org.qbittorrent.qBittorrent-old`

**Comment by pizzadude** [comment]
I found the issue, it was due to having a socks5 proxy enabled, which worked fine in the older versions. So not a problem with the flatpak.

**Comment by Erick555** [comment]
You may report this upstream.
