### ISSUE TITLE
update not happening to 4.0.4 !!!

### ISSUE THREAD

**Issue by aiamuzz** [flathub/org.qbittorrent.qBittorrent#4]
Hi,

isn't the update supposed to happen almost as soon as the new version is released ?

my current version shows as 4.0.3 ... as per the qBittorrent repo version 4.0.4 was released way back in Feb ... 

`flatpak --installation=myFlatpaks update org.qBittorrent.qbittorrent`

yields no update !!!

**Comment by TingPing** [comment]
4.0.4 was the first release ever posted here. So either the software is just bugged and shows the wrong version or you aren't using the flatpak.

**Comment by eszlari** [comment]
I guess this can be closed now.
