### ISSUE TITLE
wayland: right click menu is not fully shown

### ISSUE THREAD

**Issue by fikrillah** [flathub/org.qbittorrent.qBittorrent#56]
it's works fine on x11. 
![Cuplikan layar dari 2021-02-14 00-49-16](https://user-images.githubusercontent.com/48489341/107873094-3b362300-6ee2-11eb-80f1-822273d0cca9.png)

**Comment by eszlari** [comment]
Does work in the non-flatpak version?

**Comment by fikrillah** [comment]
same with non-flatpak version apparently. sorry.
should i close this issue?
