### ISSUE TITLE
The directory for downloads can not be selected.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.qbittorrent.qBittorrent#7]
qBittorrent version and Operating System
Qbittorrent Flatpak 4.1.0 / Ubuntu 18.04

If on linux, libtorrent and Qt version
libtorrent19 0.13.6-2build1 / Qt version 4.8.7

What is the problem
When you open "default save path" Nautilus does not allow you to select another directory.

What is the expected behavior
Select the directory

Steps to reproduce
Preferences/Downloads/Default Save Path/Nautilus window

Extra info(if any)
Screenshot: https://yadi.sk/i/kGvbGYh23VkQYu

**Comment by TingPing** [comment]
Seems like a Qt bug, the Flatpak portal cannot choose directories atm.

As a workaround you can just copy paste the path into the text field in qbittorrent.

**Comment by alexb3d** [comment]
New error, same problem.
I can write the save directory, but when I want to change the directory of an active torrent, it is impossible.
In a torrent: Right click > Set location

**Comment by alexb3d** [comment]
This problem also affects the RSS directory.
If you can not change directories, qBittorrent in Flatpak is useless.

**Comment by TingPing** [comment]
This is a bug to report against Qt but I suppose I can ping @aleixpol and @grulja to see if they are aware of this issue.

For context when a file chooser is meant for directories Gtk just avoids the portal and uses normal dialogs. It kinda sucks but it is better than being useless.

**Comment by grulja** [comment]
I'll try to fix this in Qt and backport to KDE runtime. Unfortunately there is no env var to disable portals support in Qt.

**Comment by alexb3d** [comment]
Yes, I'm sorry, it was not what I wanted to say. I am currently using Flatpak.

You can write the path in the default directory and in the RSS, but it is not possible when you want to change the path of an active torrent. Right click / Set Location.

**Comment by grulja** [comment]
I pushed a patch for review: https://codereview.qt-project.org/#/c/230089/

I test it with my test applications and it worked, but I would rather wait for review before we backport it to the runtime.

**Comment by grulja** [comment]
Patch has been accepted by upstream and merged to the runtime. Once you get update (later today or tomorrow), please verify it works correctly and let me know if there is any problem.

**Comment by alexb3d** [comment]
Hi. I have not had Qbittorrent updates but some ones from "KDE share library".
When you press the open button, the program closes immediately. I tried deleting the configuration files but still with the error.

If something works, I ran from the terminal:
flatpak run org.qbittorrent.qBittorrent/
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: image driver extension not found
libGL error: failed to load driver: radeon
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: r600


*************************************************************
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v4.1.0

Caught signal: SIGSEGV
Stack trace:
  /lib/libQt5Gui.so.5 : QFileDialogOptions::windowTitle() const+0  [0x7f6dc16abc40]
  /usr/lib/plugins/platformthemes/libqgtk3.so : ()+0x16459  [0x7f6db770a459]
  /usr/lib/plugins/platformthemes/libqgtk3.so : ()+0x16e25  [0x7f6db770ae25]
  /usr/lib/plugins/platformthemes/libqflatpak.so : ()+0x66f4  [0x7f6db77576f4]
  /lib/libQt5Widgets.so.5 : QFileDialog::setFilter(QFlags<QDir::Filter>)+0x99  [0x7f6dc1e3b591]
  /lib/libQt5Widgets.so.5 : QFileDialog::setOptions(QFlags<QFileDialog::Option>)+0x11a  [0x7f6dc1e48e9a]
  /lib/libQt5Widgets.so.5 : QFileDialog::setOption(QFileDialog::Option, bool)+0x28  [0x7f6dc1e48fb2]
  /lib/libQt5Widgets.so.5 : QFileDialog::setFileMode(QFileDialog::FileMode)+0x3d  [0x7f6dc1e4900f]
  /lib/libQt5Widgets.so.5 : QFileDialog::QFileDialog(QFileDialogArgs const&)+0x75  [0x7f6dc1e49997]
  /lib/libQt5Widgets.so.5 : QFileDialog::getExistingDirectoryUrl(QWidget*, QString const&, QUrl const&, QFlags<QFileDialog::Option>, QStringList const&)+0xc8  [0x7f6dc1e4a50a]
  /lib/libQt5Widgets.so.5 : QFileDialog::getExistingDirectory(QWidget*, QString const&, QString const&, QFlags<QFileDialog::Option>)+0xcd  [0x7f6dc1e4a737]
  qbittorrent : TransferListWidget::setSelectedTorrentsLocation()+0x97  [0x6ae0c7]
  qbittorrent() [0x7009be]
  /lib/libQt5Core.so.5 : QMetaObject::activate(QObject*, int, int, void**)+0x685  [0x7f6dc107bee5]
  /lib/libQt5Core.so.5 : QMetaObject::activate(QObject*, QMetaObject const*, int, void**)+0x23  [0x7f6dc107c2ad]
  /lib/libQt5Widgets.so.5 : QAction::triggered(bool)+0x32  [0x7f6dc1c02674]
  /lib/libQt5Widgets.so.5 : QAction::activate(QAction::ActionEvent)+0x22f  [0x7f6dc1c05723]
  /lib/libQt5Widgets.so.5 : ()+0x30c8b6  [0x7f6dc1dba8b6]
  /lib/libQt5Widgets.so.5 : ()+0x3149d0  [0x7f6dc1dc29d0]
  /lib/libQt5Widgets.so.5 : QMenu::mouseReleaseEvent(QMouseEvent*)+0xe5  [0x7f6dc1dc36ad]
  /lib/libQt5Widgets.so.5 : QWidget::event(QEvent*)+0xdc  [0x7f6dc1c538f0]
  /lib/libQt5Widgets.so.5 : QMenu::event(QEvent*)+0x1ad  [0x7f6dc1dc5b55]
  /lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x169  [0x7f6dc1c0ab17]
  /lib/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x863  [0x7f6dc1c12db9]
  qbittorrent : Application::notify(QObject*, QEvent*)+0x12  [0x4f4842]
  /lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x9a  [0x7f6dc104c572]
  /lib/libQt5Widgets.so.5 : QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)+0x353  [0x7f6dc1c11b5f]
  /lib/libQt5Widgets.so.5 : ()+0x1c22bf  [0x7f6dc1c702bf]
  /lib/libQt5Widgets.so.5 : ()+0x1c58d3  [0x7f6dc1c738d3]
  /lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x169  [0x7f6dc1c0ab17]
  /lib/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x366  [0x7f6dc1c128bc]
  qbittorrent : Application::notify(QObject*, QEvent*)+0x12  [0x4f4842]
  /lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x9a  [0x7f6dc104c572]
  /lib/libQt5Gui.so.5 : QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)+0x808  [0x7f6dc16761ca]
  /lib/libQt5Gui.so.5 : QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)+0x2c  [0x7f6dc1677aee]
  /lib/libQt5Gui.so.5 : QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x23  [0x7f6dc164db19]
  /lib/libQt5XcbQpa.so.5 : ()+0xab0da  [0x7f6dbb5b80da]
  /lib/libglib-2.0.so.0 : g_main_context_dispatch()+0x2a7  [0x7f6dbcd8e1c7]
  /lib/libglib-2.0.so.0 : ()+0x4a430  [0x7f6dbcd8e430]
  /lib/libglib-2.0.so.0 : g_main_context_iteration()+0x2c  [0x7f6dbcd8e4dc]
  /lib/libQt5Core.so.5 : QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x60  [0x7f6dc10a60ec]
  /lib/libQt5XcbQpa.so.5 : ()+0xab250  [0x7f6dbb5b8250]
  /lib/libQt5Core.so.5 : QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x23  [0x7f6dc104a33f]
  /lib/libQt5Core.so.5 : QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+0x181  [0x7f6dc104a785]
  /lib/libQt5Widgets.so.5 : QMenu::exec(QPoint const&, QAction*)+0x73  [0x7f6dc1dc0353]
  qbittorrent : TransferListWidget::displayListMenu(QPoint const&)+0x344f  [0x6b369f]
  qbittorrent() [0x700b8d]
  /lib/libQt5Core.so.5 : QMetaObject::activate(QObject*, int, int, void**)+0x685  [0x7f6dc107bee5]
  /lib/libQt5Core.so.5 : QMetaObject::activate(QObject*, QMetaObject const*, int, void**)+0x23  [0x7f6dc107c2ad]
  /lib/libQt5Widgets.so.5 : QWidget::customContextMenuRequested(QPoint const&)+0x25  [0x7f6dc1c382db]
  /lib/libQt5Widgets.so.5 : QWidget::event(QEvent*)+0x798  [0x7f6dc1c53fac]
  /lib/libQt5Widgets.so.5 : QFrame::event(QEvent*)+0x1c  [0x7f6dc1d114a6]
  /lib/libQt5Widgets.so.5 : QAbstractScrollArea::viewportEvent(QEvent*)+0x81  [0x7f6dc1d1ac5d]
  /lib/libQt5Widgets.so.5 : QAbstractItemView::viewportEvent(QEvent*)+0x267  [0x7f6dc1ea50b3]
  /lib/libQt5Widgets.so.5 : QTreeView::viewportEvent(QEvent*)+0x30  [0x7f6dc1f17fda]
  /lib/libQt5Widgets.so.5 : ()+0x26d667  [0x7f6dc1d1b667]
  /lib/libQt5Core.so.5 : QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*)+0x141  [0x7f6dc104c3c1]
  /lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x97  [0x7f6dc1c0aa45]
  /lib/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x10b1  [0x7f6dc1c13607]
  qbittorrent : Application::notify(QObject*, QEvent*)+0x12  [0x4f4842]
  /lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x9a  [0x7f6dc104c572]
  /lib/libQt5Widgets.so.5 : ()+0x1c34fb  [0x7f6dc1c714fb]
Consider installing debug symbols for packages containing files with empty function names (i.e. empty braces "()") to make your stack trace more useful

**Comment by grulja** [comment]
Ok, I managed to reproduce with qBittorrent. It's weird it works perfectly with my test application so it must be something specific to the way how qBittorent uses that file dialog. I'll investigate and fix this problem.

**Comment by grulja** [comment]
Patch is on review: https://codereview.qt-project.org/#/c/230560/. I'll merge it as soon as this is accepted.

**Comment by TingPing** [comment]
@grulja This package is still on the 5.9 runtime, does this need to move to 5.11?

**Comment by grulja** [comment]
Nope, it's not necessary, we are backporting all patches to Qt 5.9 and Qt 5.10.
